(add-hook 'haskell-mode-hook 'haskell-indentation-mod)
;(add-hook 'haskell-mode-hook 'intero-mode)
;(intero-global-mode 1)
(require 'lsp)
(require 'lsp-haskell)
(require 'lsp-ui)
(add-hook 'lsp-mode-hook 'lsp-ui-mode)
(add-hook 'haskell-mode-hook #'lsp)
(define-key lsp-ui-mode-map [remap xref-find-definitions] #'lsp-ui-peek-find-definitions)
(define-key lsp-ui-mode-map [remap xref-find-references] #'lsp-ui-peek-find-references)
